steps:
    # pull .npmrc form Cloud Stroge
    - name: gcr.io/cloud-builders/gsutil
      args: ['cp', 'gs://${_BERGLAS_BUCKET}/.npmrc', '.npmrc']
    
    # Building image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest", "."]

    # Push Images
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest"]

    # Deploy to Cloud Run
    # Setup berglas secrets
    - name: "gcr.io/cloud-builders/gcloud"
      args: [
        'run',
        'deploy',
        '${_SERVICE_NAME}',
        '--image',
        'gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest',
        '--memory',
        '1G',
        '--region', 
        'us-central1', 
        '--platform',
        'managed',
        "--concurrency",
        '4',
        '--set-env-vars',
        'DB_PASS=berglas://${_BERGLAS_BUCKET}/DB_PASS'
      ]

images: ['gcr.io/${PROJECT_ID}/${_IMAGE_NAME}:latest']